### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by malicean** [blockba5her/dispatchsystem#11]
Might be a good idea to start transferring strings to a server-wide locale file, then allow for clients to choose. I know there's a large French community, and some may want to change the file just for fun.

**Comment by DevBlocky** [comment]
Yeah I have been thinking about that it's just I don't want to deal with turning the entire thing on it's head for Localization. Maybe 3.0 though. Thanks for the input.

Also another thing that might be good: Changeable commands for ingame parts of DispatchSystem (will have to change from Reflection to do that because strings it requires constants in attributes).

**Comment by DevBlocky** [comment]
Implemented.
